import { ApiProperty } from '@nestjs/swagger';
import { IsString, Length, Matches } from 'class-validator';

export class VerifyMfaDto {
  @ApiProperty({
    description:
      '6-digit TOTP code generated by the authenticator application.',
    example: '123456',
    pattern: '^\\d{6}$',
  })
  @IsString()
  @Length(6, 6)
  @Matches(/^\d{6}$/)
  code: string;
}
